### ISSUE TITLE
Private Registry Auth

### ISSUE THREAD

**Issue by anak10thn** [orcinustools/orcinus#2]
```bash
docker login private-registry.domain
```
```yaml
services:
   app:
       image: "private-registry.domain/image:v1"
       auth: true
```
