### ISSUE TITLE
Stack Option

### ISSUE THREAD

**Issue by anak10thn** [orcinustools/orcinus#5]
add stack option for osilate and link more services
```yml
stack: "name_stack"
services:
   app:
       image: "aksaramaya/docker-http-server:v1"
```
