### ISSUE TITLE
[File System] Bind Support

### ISSUE THREAD

**Issue by anak10thn** [orcinustools/orcinus#7]
```yml
services:
   app:
       image: "aksaramaya/docker-http-server"
       volumes: 
       - "bindtest"
volumes:
   nfstest:
      type: "bind"
      source: "/mnt"
      target: "/mnt"
```
