### ISSUE TITLE
[SERVICE] constraint supports

### ISSUE THREAD

**Issue by anak10thn** [orcinustools/orcinus#8]
https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints---constraint
use : 
```yml
services:
   app:
       image: "aksaramaya/docker-http-server:v1"
       constraint: "node.role==manager"
```

node | attribute matches	|example
---|---|---|
node.id|	node ID|	node.id == 2ivku8v2gvtg4
node.hostname|	node hostname|	node.hostname != node-2
node.role|	node role: manager|	node.role == manager
node.labels|	user defined node labels|	node.labels.security == high
engine.labels|	Docker Engine’s labels|	engine.labels.operatingsystem == ubuntu 14.04
